# development:
#   sessions:
#     default:
#       uri: mongodb://user:pass@host:port/database_name
#
# test:
#   sessions:
#     default:
#       uri: mongodb://user:pass@host:port/database_name
#
# test:
#   sessions:
#     default:
#       uri: mongodb://user:pass@host:port/database_name
